/************************************************************************
 XeraAimMib.java

 Generated by mib2j from /root/inprogress/aim/mibs/XERA-AIM-MIB.
 (c)Copyright 2005 Transera Communications, Inc. All rights reserved.
************************************************************************/

package snmp.mibs;

import agentx.subagent.AgentX_SubAgent;
import agentx.syntax.*;
import agentx.pdu.AgentXProtocolException;

import snmp.mibs.XeraMib;

public class XeraAimMib {

    public static class XeraAimLoginVarbind extends AgentX_Varbind {
        XeraAimLoginVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.1",
                   value );
        }
    }


    public static class XeraAimProcessNameVarbind extends AgentX_Varbind {
        XeraAimProcessNameVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.2",
                   value );
        }
    }


    public static class XeraAimCompanyNameVarbind extends AgentX_Varbind {
        XeraAimCompanyNameVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.3",
                   value );
        }
    }


    public static class XeraAimTenantIdVarbind extends AgentX_Varbind {
        XeraAimTenantIdVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.4",
                   value );
        }
    }


    public static class XeraAimAgentIdVarbind extends AgentX_Varbind {
        XeraAimAgentIdVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.5",
                   value );
        }
    }


    public static class XeraAimAgentNameVarbind extends AgentX_Varbind {
        XeraAimAgentNameVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.6",
                   value );
        }
    }


    public static class XeraAimFilenameVarbind extends AgentX_Varbind {
        XeraAimFilenameVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.7",
                   value );
        }
    }


    public static class XeraAimDatatypeVarbind extends AgentX_Varbind {
        XeraAimDatatypeVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.8",
                   value );
        }
    }


    public static class XeraAimTpgIpAddressVarbind extends AgentX_Varbind {
        XeraAimTpgIpAddressVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.9",
                   value );
        }
    }


    public static class XeraAimOperationTypeVarbind extends AgentX_Varbind {
        XeraAimOperationTypeVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.10",
                   value );
        }
    }


    public static class XeraAimHostnameVarbind extends AgentX_Varbind {
        XeraAimHostnameVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.11",
                   value );
        }
    }


    public static class XeraAimConfigAgentUrlVarbind extends AgentX_Varbind {
        XeraAimConfigAgentUrlVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.12",
                   value );
        }
    }


    public static class XeraAimXpathVarbind extends AgentX_Varbind {
        XeraAimXpathVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.13",
                   value );
        }
    }


    public static class XeraAimXsltFileVarbind extends AgentX_Varbind {
        XeraAimXsltFileVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.14",
                   value );
        }
    }


    public static class XeraAimErrorMessageVarbind extends AgentX_Varbind {
        XeraAimErrorMessageVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.15",
                   value );
        }
    }


    public static class XeraAimDatabaseUrlVarbind extends AgentX_Varbind {
        XeraAimDatabaseUrlVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.16",
                   value );
        }
    }


    public static class XeraAimDatabaseUserVarbind extends AgentX_Varbind {
        XeraAimDatabaseUserVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.17",
                   value );
        }
    }


    public static class XeraAimAcgUrlVarbind extends AgentX_Varbind {
        XeraAimAcgUrlVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.18",
                   value );
        }
    }


    public static class XeraAimMessageVarbind extends AgentX_Varbind {
        XeraAimMessageVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.19",
                   value );
        }
    }


    public static class XeraAimRetryCountVarbind extends AgentX_Varbind {
        XeraAimRetryCountVarbind( long value ) throws AgentXProtocolException {
            super( AgentX_Varbind.INTEGER,
                   "1.3.6.1.4.1.21257.22.1.1.20",
                   value );
        }
    }


    public static class XeraAimUrlVarbind extends AgentX_Varbind {
        XeraAimUrlVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.21",
                   value );
        }
    }


    public static class XeraAimCommandVarbind extends AgentX_Varbind {
        XeraAimCommandVarbind( String value ) throws AgentXProtocolException {
            super( AgentX_Varbind.OCTET_STRING,
                   "1.3.6.1.4.1.21257.22.1.1.22",
                   value );
        }
    }


    public static class XeraAimAgentDoesNotExist extends snmp.Notification {
        public XeraAimAgentDoesNotExist(
                                              String xeraAimProcessName,
                                              String xeraAimLogin,
                                              String xeraAimCompanyName,
                                              String xeraAimTenantId ) throws AgentXProtocolException
        {
            super( new AgentX_Oid("1.3.6.1.4.1.21257.22.1000.1") );
            AgentX_VarbindList arguments = getArguments();
            arguments.add( new XeraAimProcessNameVarbind(xeraAimProcessName) );
            arguments.add( new XeraAimLoginVarbind(xeraAimLogin) );
            arguments.add( new XeraAimCompanyNameVarbind(xeraAimCompanyName) );
            arguments.add( new XeraAimTenantIdVarbind(xeraAimTenantId) );
        }
    }

    public static class XeraAimIncorrectPassword extends snmp.Notification {
        public XeraAimIncorrectPassword(
                                              String xeraAimProcessName,
                                              String xeraAimAgentId,
                                              String xeraAimAgentName,
                                              String xeraAimLogin,
                                              String xeraAimTenantId ) throws AgentXProtocolException
        {
            super( new AgentX_Oid("1.3.6.1.4.1.21257.22.1000.2") );
            AgentX_VarbindList arguments = getArguments();
            arguments.add( new XeraAimProcessNameVarbind(xeraAimProcessName) );
            arguments.add( new XeraAimAgentIdVarbind(xeraAimAgentId) );
            arguments.add( new XeraAimAgentNameVarbind(xeraAimAgentName) );
            arguments.add( new XeraAimLoginVarbind(xeraAimLogin) );
            arguments.add( new XeraAimTenantIdVarbind(xeraAimTenantId) );
        }
    }

    public static class XeraAimWrongTenantName extends snmp.Notification {
        public XeraAimWrongTenantName(
                                              String xeraAimProcessName,
                                              String xeraAimAgentId,
                                              String xeraAimAgentName,
                                              String xeraAimLogin,
                                              String xeraAimCompanyName,
                                              String xeraAimTenantId ) throws AgentXProtocolException
        {
            super( new AgentX_Oid("1.3.6.1.4.1.21257.22.1000.3") );
            AgentX_VarbindList arguments = getArguments();
            arguments.add( new XeraAimProcessNameVarbind(xeraAimProcessName) );
            arguments.add( new XeraAimAgentIdVarbind(xeraAimAgentId) );
            arguments.add( new XeraAimAgentNameVarbind(xeraAimAgentName) );
            arguments.add( new XeraAimLoginVarbind(xeraAimLogin) );
            arguments.add( new XeraAimCompanyNameVarbind(xeraAimCompanyName) );
            arguments.add( new XeraAimTenantIdVarbind(xeraAimTenantId) );
        }
    }

    public static class XeraAimInvalidLogin extends snmp.Notification {
        public XeraAimInvalidLogin(
                                              String xeraAimProcessName,
                                              String xeraAimLogin,
                                              String xeraAimCompanyName,
                                              String xeraAimTpgIpAddress ) throws AgentXProtocolException
        {
            super( new AgentX_Oid("1.3.6.1.4.1.21257.22.1000.4") );
            AgentX_VarbindList arguments = getArguments();
            arguments.add( new XeraAimProcessNameVarbind(xeraAimProcessName) );
            arguments.add( new XeraAimLoginVarbind(xeraAimLogin) );
            arguments.add( new XeraAimCompanyNameVarbind(xeraAimCompanyName) );
            arguments.add( new XeraAimTpgIpAddressVarbind(xeraAimTpgIpAddress) );
        }
    }

    public static class XeraAimStorageError extends snmp.Notification {
        public XeraAimStorageError(
                                              String xeraAimProcessName,
                                              String xeraAimFilename,
                                              String xeraAimDatatype,
                                              String xeraAimOperationType ) throws AgentXProtocolException
        {
            super( new AgentX_Oid("1.3.6.1.4.1.21257.22.1000.5") );
            AgentX_VarbindList arguments = getArguments();
            arguments.add( new XeraAimProcessNameVarbind(xeraAimProcessName) );
            arguments.add( new XeraAimFilenameVarbind(xeraAimFilename) );
            arguments.add( new XeraAimDatatypeVarbind(xeraAimDatatype) );
            arguments.add( new XeraAimOperationTypeVarbind(xeraAimOperationType) );
        }
    }

    public static class XeraAimServerConfigError extends snmp.Notification {
        public XeraAimServerConfigError(
                                              String xeraAimProcessName,
                                              String xeraAimFilename,
                                              String xeraAimHostname,
                                              String xeraAimConfigAgentUrl,
                                              String xeraAimXpath,
                                              String xeraAimXsltFile,
                                              String xeraAimErrorMessage ) throws AgentXProtocolException
        {
            super( new AgentX_Oid("1.3.6.1.4.1.21257.22.1000.6") );
            AgentX_VarbindList arguments = getArguments();
            arguments.add( new XeraAimProcessNameVarbind(xeraAimProcessName) );
            arguments.add( new XeraAimFilenameVarbind(xeraAimFilename) );
            arguments.add( new XeraAimHostnameVarbind(xeraAimHostname) );
            arguments.add( new XeraAimConfigAgentUrlVarbind(xeraAimConfigAgentUrl) );
            arguments.add( new XeraAimXpathVarbind(xeraAimXpath) );
            arguments.add( new XeraAimXsltFileVarbind(xeraAimXsltFile) );
            arguments.add( new XeraAimErrorMessageVarbind(xeraAimErrorMessage) );
        }
    }

    public static class XeraAimProvisioningDataFetchFailed extends snmp.Notification {
        public XeraAimProvisioningDataFetchFailed(
                                              String xeraAimProcessName,
                                              String xeraAimDatatype,
                                              String xeraAimDatabaseUrl,
                                              String xeraAimDatabaseUser,
                                              String xeraAimErrorMessage ) throws AgentXProtocolException
        {
            super( new AgentX_Oid("1.3.6.1.4.1.21257.22.1000.7") );
            AgentX_VarbindList arguments = getArguments();
            arguments.add( new XeraAimProcessNameVarbind(xeraAimProcessName) );
            arguments.add( new XeraAimDatatypeVarbind(xeraAimDatatype) );
            arguments.add( new XeraAimDatabaseUrlVarbind(xeraAimDatabaseUrl) );
            arguments.add( new XeraAimDatabaseUserVarbind(xeraAimDatabaseUser) );
            arguments.add( new XeraAimErrorMessageVarbind(xeraAimErrorMessage) );
        }
    }

    public static class XeraAimAcgNotificationFailed extends snmp.Notification {
        public XeraAimAcgNotificationFailed(
                                              String xeraAimProcessName,
                                              String xeraAimAcgUrl,
                                              String xeraAimMessage,
                                              String xeraAimErrorMessage,
                                              long xeraAimRetryCount ) throws AgentXProtocolException
        {
            super( new AgentX_Oid("1.3.6.1.4.1.21257.22.1000.8") );
            AgentX_VarbindList arguments = getArguments();
            arguments.add( new XeraAimProcessNameVarbind(xeraAimProcessName) );
            arguments.add( new XeraAimAcgUrlVarbind(xeraAimAcgUrl) );
            arguments.add( new XeraAimMessageVarbind(xeraAimMessage) );
            arguments.add( new XeraAimErrorMessageVarbind(xeraAimErrorMessage) );
            arguments.add( new XeraAimRetryCountVarbind(xeraAimRetryCount) );
        }
    }

    public static class XeraAimNotificationFailed extends snmp.Notification {
        public XeraAimNotificationFailed(
                                              String xeraAimProcessName,
                                              String xeraAimCommand,
                                              String xeraAimUrl,
                                              String xeraAimTenantId,
                                              String xeraAimAgentId,
                                              String xeraAimErrorMessage,
                                              long xeraAimRetryCount ) throws AgentXProtocolException
        {
            super( new AgentX_Oid("1.3.6.1.4.1.21257.22.1000.9") );
            AgentX_VarbindList arguments = getArguments();
            arguments.add( new XeraAimProcessNameVarbind(xeraAimProcessName) );
            arguments.add( new XeraAimCommandVarbind(xeraAimCommand) );
            arguments.add( new XeraAimUrlVarbind(xeraAimUrl) );
            arguments.add( new XeraAimTenantIdVarbind(xeraAimTenantId) );
            arguments.add( new XeraAimAgentIdVarbind(xeraAimAgentId) );
            arguments.add( new XeraAimErrorMessageVarbind(xeraAimErrorMessage) );
            arguments.add( new XeraAimRetryCountVarbind(xeraAimRetryCount) );
        }
    }

    public static class XeraAimPasswordPolicyNotProvisioned extends snmp.Notification {
        public XeraAimPasswordPolicyNotProvisioned(
                                              String xeraAimProcessName,
                                              String xeraAimTenantId,
                                              String xeraAimAgentId,
                                              String xeraAimErrorMessage ) throws AgentXProtocolException
        {
            super( new AgentX_Oid("1.3.6.1.4.1.21257.22.1000.10") );
            AgentX_VarbindList arguments = getArguments();
            arguments.add( new XeraAimProcessNameVarbind(xeraAimProcessName) );
            arguments.add( new XeraAimTenantIdVarbind(xeraAimTenantId) );
            arguments.add( new XeraAimAgentIdVarbind(xeraAimAgentId) );
            arguments.add( new XeraAimErrorMessageVarbind(xeraAimErrorMessage) );
        }
    }
}
